# editable service contents
contents:
  categories: [ aws ]
# service configuration
config:
  contents:
    sections:
      aws:
        name: Provider
        description: Configuration specific to AWS
        sort: 2
        fields:
          aws/key_name:
            name: Key Pair Name
            description: Key Pair Name to use
            type: text
            default:
            sort: 1
            editable: [ none, destroyed ]
          aws/key_material:
            name: Key Pair Material
            description: Key Pair Material to use
            type: text
            default:
            sort: 2
            editable: [ none, destroyed ]
