# service configuration
config:
  doctype: config
  impl: c2core.logical.config.Config
  contents:
    sections:
      service:
        name: Service
        description: Basic Service configuration fields
        sort: 1
        fields:
          service/abbreviation:
            name: Service Abbreviation
            description: Abbreviation for this service used in AWS names
            type: text
            default: base
            sort: 0
            editable: [ none, destroyed ]
          service/path:
            name: Service Path
            description: Path to this service in the deployment repository
            type: text
            default:
            sort: 1
            editable: [ none, destroyed ]
