# editable service contents
contents:
  categories: [ database ]
# service configuration
config:
  contents:
    sections:
      database:
        name: Database
        description: Configuration for database components
        sort: 13
        fields:
          database/username:
            name: Database Username
            description: Username used to access the database
            type: text
            sort: 0
            default: 
          database/password:
            name: Database Password
            description: Password used to access the database
            type: text
            sort: 1
            default:
          database/type:
            name: Database Type
            description: Type of database (postgresql, mysql, etc)
            type: text
            sort: 2
            default: 
          database/host:
            name: Database Hostname
            description: Hostname used to access the database
            type: text
            sort: 3
            default:
          database/port:
            name: Database Port
            description: Port used to access the database
            type: text
            sort: 4
            default:  
