# service configuration
config:
  contents:
    sections:
      ec2-deploy:
        name: EC2 Deployment
        description: Configuration for EC2 Instance deployments
        sort: 9
        fields:
          ec2-deploy/mechanism:
            name: Deploy Mechanism
            description: Mechanism for triggering deployments
            type: text
            default: ssh
            sort: 1
            env_key: DEPLOY_MECHANISM
          ec2-deploy/username:
            name: Deploy Username
            description: Username used to trigger deployment commands
            type:
            default: ubuntu
            sort: 2
            env_key: DEPLOY_USERNAME
          ec2-deploy/command:
            name: Deploy Command
            description: Command to run when triggering a deploy
            type: url
            default: source .opdemand && sudo apt-get update && sudo apt-get dist-upgrade -yq
            sort: 3
          ec2-deploy/key:
            name: Deploy Key
            description: Private key used to trigger deployment commands
            type:
            default:
            sort: 4
            env_key: DEPLOY_KEY
          ec2-deploy/repository_url:
            name: Repository URL
            description: Git repository URL containing deployment code
            type: repository-url
            default: git://github.com/opdemand/opdemand-ubuntu.git
            sort: 5
            env_key: DEPLOY_REPOSITORY_URL
          ec2-deploy/repository_revision:
            name: Repository Revision
            description: Repository revision to pull latest code from
            type: text
            default: origin/master
            sort: 6
            env_key: DEPLOY_REPOSITORY_REVISION
          ec2-deploy/repository_path:
            name: Repository Path
            description: Path to place deployment repository
            type: text
            default: /var/lib/opdemand
            sort: 7
            env_key: DEPLOY_REPOSITORY_PATH            
          ec2-deploy/debug:
            name: Deploy Debugging
            description: Produce debug output from deploy scripts
            type: boolean
            default: false
            sort: 8
            env_key: DEPLOY_DEBUG
