# editable service contents
contents:
  categories: [ cache ]
# service configuration
config:
  contents:
    sections:
      cache:
        name: Cache
        description: Configuration for cache components
        sort: 14
        fields:
          cache/host:
            name: Cache Hostname
            description: Hostname used to access the cache service
            type: text
            sort: 0
            default: localhost
            env_key: CACHE_HOSTNAME
          cache/username:
            name: Cache Username
            description: Username used to access the cache
            type: text
            sort: 1
            default:
            env_key: CACHE_USERNAME
          cache/password:
            name: Cache Password
            description: Password used to access the cache
            type: text
            sort: 2
            default:
            env_key: CACHE_PASSWORD
          cache/type:
            name: Cache Type
            description: Type of cache (redis, memcached, varnish)
            type: text
            sort: 3
            default:
            env_key: CACHE_TYPE
          cache/port:
            name: Cache Port
            description: Port used to access the database
            type: text
            sort: 4
            default:  
            env_key: CACHE_PORT            
          cache/size:
            name: Cache Size
            description: Cache size in megabytes
            type: text
            sort: 5
            default:
            env_key: CACHE_SIZE
