# editable service contents
contents:
  categories: [ chef ]
  description: Configuration for Chef Solo configuration management
# service configuration
config:
  contents:
    sections:
      chef:
        name: Chef Solo
        description: Configuration for Chef Solo configuration management
        sort: 13
        fields:
          chef-solo/recipes:
            name: Chef Recipies
            description: List of Chef Recipies to apply
            type: list
            default: [ ]
            sort: 1
            env_key: CHEF_RECIPIES
          chef-solo/repository_url:
            name: Repository URL
            description: Repository URL containing Chef cookbooks
            type: repository-url
            default: 
            sort: 2
            env_key: CHEF_REPOSITORY_URL
          chef-solo/repository_key:
            name: Repository Key
            description: SSH private key to access the repository
            type: textarea
            default:
            sort: 3
            env_key: CHEF_REPOSITORY_KEY
          chef-solo/repository_path:
            name: Repository Path
            description: Path to local copy of repository
            type: text
            default: /var/chef-solo/cookbooks
            sort: 4
            env_key: CHEF_REPOSITORY_PATH
          chef-solo/repository_revision:
            name: Repository Revision
            description: Repository revision to pull latest code from 
            type: text
            default:
            sort: 5
            env_key: CHEF_REPOSITORY_REVISION
          chef-solo/debug:
            name: Chef Debugging
            description: Debug flag for Chef runs
            type: boolean
            default: false
            sort: 6
            env_key: CHEF_DEBUG
