contents:
  description: Configuration for an EBS volume
config:
  contents:
    sections:
      ebs-volume:
        name: EBS Volume
        description: Configuration for an EBS volume
        sort: 7
        fields:
          ebs-volume/region_name:
            name: Region
            description: Name of AWS region
            type: clouds
            default:
            required: true
            sort: 1
            editable: [ none, destroyed ]
          ebs-volume/zone_name:
            name: Zone
            description: Name of AWS zone to use
            type: zone
            default:
            required: true
            sort: 2
            editable: [ none, destroyed ]
          ebs-volume/id:
            name: Volume ID
            description: Unique ID of the EBS Volume
            type: text
            sort: 3
            editable: [ none, destroyed ]
          ebs-volume/size:
            name: Size
            description: Size of volume in GB
            type: int
            default: 10
            sort: 4
            editable: [ none, destroyed ]
          ebs-volume/iops:
            name: IOPS
            description: Provisioned IOPS (100-1000, optional)
            default:
            sort: 5
            editable: [ none, destroyed ]
          ebs-volume/snapshot_id:
            name: Snapshot ID
            description: Source snapshot ID for this volume (optional)
            default:
            sort: 6
            editable: [ none, destroyed ]
          ebs-volume/type:
            name: Type
            description: Type of volume (standard or IOPS)
            default: standard
            sort: 7
            editable: [ none, destroyed ]
          ebs-volume/attach_time:
            name: Attach Time
            description: Time the volume was last attached
            type: text
            editable: []
            sort: 8
          ebs-volume/create_time:
            name: Create Time
            description: Time the volume was created
            type: text
            sort: 9
            editable: [ ]
