contents:
  description: Configuration for EC2 Instance deployments
# service configuration
config:
  contents:
    sections:
      ec2-deploy:
        name: EC2 Deployment
        description: Configuration for EC2 Instance deployments
        sort: 9
        fields:
          ec2-deploy/mechanism:
            name: Deploy Mechanism
            description: Mechanism for triggering deployments
            type: text
            default: ssh
            sort: 1
            env_key: DEPLOY_MECHANISM
          ec2-deploy/username:
            name: Deploy Username
            description: Username used to trigger deployment commands
            type:
            default: ubuntu
            sort: 2
            env_key: DEPLOY_USERNAME
          ec2-deploy/command:
            name: Deploy Command
            description: Command to trigger deploy on an instance
            type: textarea
            default: |
              source .opdemand
              # if git-deploy environment variables exist, use them
              if [ ! -z $DEPLOY_REPOSITORY_URL ]; then              
                # run build on first deploy, only if necessary
                if [ ! -e /var/lib/opdemand ]; then
                  echo "Waiting for Ubuntu cloud-init to finish"
                  while [ ! -z "`ps auxw |grep cloud-init | grep -v grep`" ] ; do
                    sleep 1
                  done
                  echo "Ubuntu cloud-init complete, continuing initial instance build..."
                  sudo apt-get install -yq --force-yes git 
                  sudo mkdir -p /var/cache/opdemand
                  sudo mkdir -p /var/log/opdemand
                  # clone the deployment repository and checkout the requested revision
                  sudo git clone $DEPLOY_REPOSITORY_URL /var/lib/opdemand
                  cd /var/lib/opdemand && sudo git checkout -q -f $DEPLOY_REPOSITORY_REVISION
                  # run build script
                  sudo -E /var/lib/opdemand/$BUILD_SCRIPT_PATH
                  # fix permissions
                  sudo chown -R ubuntu:ubuntu /var/lib/opdemand /var/cache/opdemand /var/log/opdemand
                fi
                # run the idempotent deploy script
                exec /var/lib/opdemand/$DEPLOY_SCRIPT_PATH
              fi
            sort: 3
          ec2-deploy/key:
            name: Deploy Key
            description: Private key used to trigger deployment commands
            type: text
            default:
            sort: 4
            required: true
            env_key: DEPLOY_KEY
          ec2-deploy/debug:
            name: Deploy Debugging
            description: Produce debug output from deploy scripts
            type: boolean
            default: false
            sort: 5
            value: false
            env_key: DEPLOY_DEBUG
