contents:
  description: Configuration for EC2 key pairs  
config:
  contents:
    sections:
      ec2-eip:
        name: EC2 Elastic IP
        description: Configuration for EC2 key pairs
        sort: 5
        fields:
          ec2-eip/region_name:
            name: Region
            description: Name of AWS region
            type: clouds
            default:
            required: true
            sort: 1
            editable: [ none, destroyed ]
          ec2-eip/public_ip:
            name: Public IP
            description: Public address of the Elastic IP
            type: text
            default:
            sort: 2
            editable: []
          ec2-eip/dns_name:
            name: Public DNS Name
            description: Public DNS name for the Elastic IP
            type: text
            default:
            sort: 3
            editable: []