contents:
  description: Configuration for EC2 security groups  
config:
  contents:
    sections:
      ec2-sg:
        name: EC2 Security Group
        description: Configuration for EC2 security groups
        sort: 6
        fields:
          ec2-sg/region_name:
            name: Region
            description: Name of AWS region
            type: clouds
            default:
            required: true
            sort: 1
            editable: [ none, destroyed ]
          ec2-sg/name:
            name: Name
            description: Name of EC2 Security Group
            type: text
            default:
            required: true
            sort: 2
            editable: [ none, destroyed ]
          ec2-sg/description:
            name: Description
            description: Description of EC2 Security Group
            type: text
            default: Managed by OpDemand
            sort: 3
            editable: [ none, destroyed ]
          ec2-sg/rules:
            name: Rules
            description: Security group rules
            type: list
            default: [ "0.0.0.0/0,tcp,22,22" ]
            sort: 4
            editable: [ none, destroyed ]
          ec2-sg/id:
            name: Group ID
            description: ID of EC2 Security Group
            type: text
            default:
            sort: 5
            editable: [ none, destroyed ]