contents:
  description: Configuration for a Heroku Application
config:
  contents:
    sections:
      heroku-app:
        name: Heroku Application
        description: Configuration for a Heroku Application
        sort: 1
        fields:
          heroku-app/region:
            name: Heroku Region
            description: Heroku Region Name
            type: clouds
            default:
            required: true
            sort: 1
            editable: []
          heroku-app/name:
            name: Application Name 
            description: Name of the Heroku Application
            type: text
            default:
            sort: 2
            editable: [ none, destroyed ]
          heroku-app/repository_url:
            name: Git Repository
            description: Source URL of Git Repository
            type: repository-url
            default:
            required: true
            sort: 3
            editable: [ none, destroyed ]
          heroku-app/repository_branch:
            name: Git Repository Branch
            description: Branch, tag or SHA from the source Git Repository
            type: repository-branch
            default: master
            required: true
            sort: 4
          heroku-app/dyno_map:
            name: Dyno Map
            description: Map of worker types and number of dynos
            type: map
            default: { 'web': 1 }
            sort: 5
          heroku-app/config:
            name: Config Variables
            description: Environment variables passed to the Heroku application
            type: map
            default: {}
            sort: 6
          heroku-app/processes:
            name: Processes
            description: Map of active process for this application
            type: map
            default: {}
            sort: 7
          heroku-app/releases:
            name: Releases
            description: List of releases to this application
            type: list
            default: []
            sort: 8
          heroku-app/private_key:
            name: Private key
            description: Private key used for cloning and pushing to Heroku
            type: textarea
            default:
            sort: 9
            editable: [ none, destroyed ]
          heroku-app/stack:
            name: Heroku Stack
            description: Name of Heroku application stack to use
            type: text
            default: cedar
            sort: 10
