# editable service contents
contents:
  categories: [ database, mongodb ]
  description: Configuration for MongoDB clients
# service configuration
config:
  contents:
    sections:
      mongodb-client:
        name: MongoDB Client
        description: Configuration for MongoDB clients
        sort: 17
        fields:
          mongodb-client/hostnames:
            name: Hostnames
            description: List of MongoDB server hostnames
            type: list
            sort: 1
            env_key: MONGODB_HOSTS
          mongodb-client/username:
            name: Username
            description: Username for MongoDB client access
            type: text
            sort: 2
            default:
            env_key: MONGODB_USERNAME
          mongodb-client/password:
            name: Password
            description: Password for MongoDB client access
            type: text
            sort: 3
            default:
            env_key: MONGODB_PASSWORD
          mongodb-client/port:
            name: Server Port
            description: Port for database listener
            type: text
            sort: 4
            default:
            env_key: MONGODB_PORT
          mongodb-client/replset:
            name: Replica Set Name
            description: Name of MongoDB Replica Set
            type: text
            sort: 5
            default: 
            env_key: MONGODB_REPLSET