contents:
  categories: [ database, mysql ]
  description: Configuration for MySQL clients
config:
  contents:
    sections:
      mysql-client:
        name: MySQL Client
        description: Configuration for MySQL clients
        sort: 13
        fields:
          mysql-client/host:
            name: Hostname
            description: Hostname used for MySQL client access
            type: text
            sort: 1
            default:
            env_key: MYSQL_HOST
          mysql-client/port:
            name: Port
            description: Port used for MySQL client access
            type: text
            sort: 2
            default:
            env_key: MYSQL_PORT
          mysql-client/username:
            name: Username
            description: Username used for MySQL client access
            type: text
            sort: 3
            default:
            env_key: MYSQL_USERNAME              
          mysql-client/password:
            name: Password
            description: Password used for MySQL client access
            type: password
            sort: 4
            default:
            env_key: MYSQL_PASSWORD
          mysql-client/db_name:
            name: Database Name
            description: Database name used for MySQL client access
            type: text
            sort: 5
            default:
            env_key: MYSQL_DBNAME