contents:
  categories: [ database, postgres ]
  description: Configuration for PostgreSQL clients
config:
  contents:
    sections:
      postgresql-client:
        name: PostgreSQL Client
        description: Configuration for database components
        sort: 14
        fields:
          postgresql-client/host:
            name: Hostname
            description: Hostname used for PostgreSQL client access
            type: text
            sort: 1
            default:
            env_key: POSTGRES_HOST
          postgresql-client/port:
            name: Port
            description: Port used for PostgreSQL client access
            type: text
            sort: 2
            default:
            env_key: POSTGRES_PORT            
          postgresql-client/username:
            name: Username
            description: Username used for PostgreSQL client access
            type: text
            sort: 3
            default:
            env_key: POSTGRES_USERNAME              
          postgresql-client/password:
            name: Password
            description: Password used for PostgreSQL client access
            type: password
            sort: 4
            default:
            env_key: POSTGRES_PASSWORD
          postgresql-client/db_name:
            name: Database Name
            description: Database name used for PostgreSQL client access
            type: text
            sort: 5
            default:
            env_key: POSTGRES_DBNAME