contents:
  categories: [ database, postgres ]
  description: Configuration for PostgreSQL servers
config:
  contents:
    sections:
      postgresql-server:
        name: PostgreSQL Server
        description: Configuration for PostgreSQL servers
        sort: 14
        fields:
          postgresql-server/port:
            name: Port
            description: Port used for PostgreSQL server listener
            type: text
            sort: 1
            default: 5432
            env_key: POSTGRES_SERVER_PORT
          postgresql-server/bind:
            name: Bind
            description: Bind address for PostgreSQL server listener
            type: text
            sort: 2
            default: "*"
            env_key: POSTGRES_SERVER_BIND
          postgresql-server/username:
            name: Username
            description: Optional username for PostgreSQL client access
            type: text
            sort: 3
            default:
            env_key: POSTGRES_SERVER_USERNAME              
          postgresql-server/password:
            name: Password
            description: Optional password for PostgreSQL client access
            type: password
            sort: 4
            default:
            env_key: POSTGRES_SERVER_PASSWORD
          postgresql-server/db_name:
            name: Database Name
            description: Optional database name for PostgreSQL client access
            type: text
            sort: 5
            default:
            env_key: POSTGRES_SERVER_DBNAME