# editable service contents
contents:
  categories: [ mq, rabbitmq ]
  description: Configuration for RabbitMQ messaging
# service configuration
config:
  contents:
    sections:
      rabbitmq:
        name: RabbitMQ
        description: Configuration for RabbitMQ messaging
        sort: 15
        fields:
          rabbitmq/nodename:
            name: Node Name
            description: Node name used for clustering
            type: text
            sort: 0
            default:
            env_key: RABBITMQ_NODENAME
          rabbitmq/port:
            name: Listener Port
            description: TCP Port to listen on 
            type: text
            sort: 1
            default: 5672
            env_key: RABBITMQ_PORT
          rabbitmq/bind:
            name: Bind Address
            description: Address to bind to for listening
            type: text
            sort: 2
            default: ""
            env_key: RABBITMQ_BIND