config:
  # server/deploy configuration
  server/repository_url: git://github.com/opdemand/opdemand-ubuntu.git
  server/build_script: scripts/build_example.sh
  server/deploy_script: scripts/deploy_example.sh
  # network configuration
  network/access_protocol: ssh
  network/access_cidr: 0.0.0.0/0
  network/access_port: 22
  network/admin_cidr: 0.0.0.0/0 # SECURITY: change to allow only trusted source networks
  network/admin_port: 22
# publish to service consumers
publish:
  - name: Access URL
    description: URL used to access this service
    template: "%(network/access_protocol)s://%(server/admin_user)s@%(network/access_host)s:%(network/access_port)s"
