# -*- test-case-name: c2server.tests.platform.NodejsRedis1x1Test -*-
name: Node.js/Redis 1x1
description: >
             Node.js environment consisting of a Key Pair, Security Group, and
             two EC2 instances. Installs the Redis key/val store on one
             instance and the Node.js web framework on the other, listening on 3000/tcp, 
             all powered by a configurable GitHub repository.
path: nodejs/redis/1x1
include: [ aws, base, network, server, puppet, application, cache ]
config:
  network/access_port: 3000
  network/admin_port: 22
  application/repository_url: git://github.com/opdemand/c2-nodejs-helloworld.git
  cache/password: changeme123.
stack:
  - name: Security
    description: Provides security infrastructure
    include: [ ]
    components:
      - type: aws-keypair
        include: [ ]
  - name: Network
    description: Provides network infrastructure
    include: [ ]
    components:
      - type: aws-sg
        include: [ network ]
  - name: Cache
    description: Provides caching services
    include: [ ]
    components:
      - type: aws-instance
        include: [ network, cache, aws, server, puppet  ]
        name: Redis
        config:
          server/hostname: redis
          server/build_script: build.sh
          server/deploy_script: deploy.cache.sh
        output:
          database/host: public_dns_name
    monitor:
      protocol: tcp
      port: 6379
  - name: Application
    description: Provides database services
    include: [ ]
    components:
      - type: aws-instance
        include: [ network, application, aws, server, puppet  ]
        name: Node
        config:
          server/hostname: node
          server/build_script: build.sh
          server/deploy_script: deploy.app.sh
        output:
          network/access_host: public_dns_name
          network/admin_host: public_dns_name
    monitor:
      protocol: tcp
      port: 3000
publish:
  - name: Access URL
    description: URL used to access this service
    template: http://%(network/access_host)s:%(network/access_port)s
