include: [ puppet ]
config:
  # server/deploy configuration
  server/repository_url: git://github.com/opdemand/opdemand-rhel.git
  server/build_script: scripts/build_puppet.sh
  server/deploy_script: scripts/deploy_puppet.sh
  # rally customizations
  server/admin_user: ec2-user
  server/image_id: ami-48da5578
  aws/region_name: us-west-2
  # network configuration
  network/access_protocol: ssh
  network/access_cidr: 0.0.0.0/0
  network/access_port: 22
  network/admin_cidr: 0.0.0.0/0 # SECURITY: change to allow only trusted source networks
  network/admin_port: 22
# publish to service consumers
publish:
  - name: Access URL
    description: URL used to access this service
    template: "%(network/access_protocol)s://%(server/admin_user)s@%(network/access_host)s:%(network/access_port)s"
