# -*- test-case-name: c2server.tests.platform.PhpMysql1nodeTest -*-
name: PHP/MySQL 1 Node
description: >
             Single node PHP environment consisting of a Key Pair, Security
             Group, and a single EC2 instance. Installs the Nginx web server,
             PHP via FastCGI, and the MySQL database.  The web server
             listens at 80/tcp and is powered by a configurable GitHub repository.
path: php/mysql/1node
include: [ aws, base, network, server, database, application ]
config:
  network/access_port: 80
  network/admin_port: 22
  application/repository_url: git://github.com/opdemand/c2-lamp-php.git
stack:
  - name: Security
    description: Provides security infrastructure
    include: [ ] 
    components:
      - type: aws-keypair
        include: [ ] 
  - name: Network
    description: Provides network infrastructure
    include: [ ] 
    components:
      - type: aws-sg
        include: [ network ] 
  - name: Server
    description: Provides generic services
    include: [ ] 
    components:
      - type: aws-instance
        name: Nginx/MySQL
        include: [ server, aws, database, application ] 
        config:
          server/hostname: server
          server/build_script: build.sh
          server/deploy_script: deploy.sh
        output:
          network/access_host: public_dns_name
          network/admin_host: public_dns_name
    monitor:
      protocol: tcp
      port: 22
publish:
  - name: Admin URL
    description: URL used to administer this service
    template: ssh://ubuntu@%(network/admin_host)s
  - name: Access URL
    description: URL used to access this service
    template: http://%(network/access_host)s
