# -*- test-case-name: c2server.tests.platform.NodejsDualTest -*-
name: Node.js Dual-node with ELB
path: nodejs/dual
include: [ aws, base, network, server, puppet, application ]
config:
  network/access_port: 80
  network/admin_port: 22
  application/repository_url: git://github.com/opdemand/c2-nodejs-helloworld.git
stack:
  - name: Security
    description: Provides security infrastructure
    include: [ ] 
    components:
      - type: aws-keypair
        include: [ ] 
  - name: Network
    description: Provides network infrastructure
    include: [ ] 
    components:
      - type: aws-sg
        include: [ network ] 
  - name: Server
    description: Provides generic services
    include: [ ] 
    components:
      - type: aws-instance
        include: [ aws, network, server, puppet, application ] 
        name: Node.js 1
        config:
          server/hostname: node1
          server/build_script: build.sh
          server/deploy_script: deploy.sh
        output:
          lb/instances: [ instance_id ]
          # make the first node the admin host
          network/admin_host: public_dns_name
      - type: aws-instance
        include: [ aws, network, server, puppet, application ] 
        name: Node.js 2
        config:
          server/hostname: node2
          server/build_script: build.sh
          server/deploy_script: deploy.sh
        output:
          lb/instances: [ instance_id ]
    monitor:
      protocol: tcp
      port: 3000
  - name: Load Balancing
    description: Provides load balancing services
    include: [ ] 
    components:
      - type: aws-elb
        include: [ ] 
        name: ELB
        config:
          lb/listeners: [ "(80, 3000, TCP)" ]
          lb/target: HTTP:3000/
        output:
          network/access_host: dns_name
    monitor:
      protocol: tcp
      port: 80
      target: dns_name
publish:
  - name: Admin URL
    description: URL used to administer this service
    template: ssh://ubuntu@%(network/admin_host)s:%(network/admin_port)s
  - name: Access URL
    description: URL used to access this service
    template: mysql://%(network/access_host)s:%(network/access_port)s
