# -*- test-case-name: c2server.tests.platform.NodejsProdTest -*-
name: Node.js with PostgreSQL (2-node)
description: >
             Node.js server environment consisting of a Key Pair, Security
             Group, an EC2 instance with a PostgreSQL database server, and
             a node.js EC2 instance. Installs latest compiled node available
             via Ubuntu PPAs. Starts a Node.js upstart daemon listening on
             3000/tcp, powered by a configurable GitHub repository.
path: nodejs/prod
include: [ aws, base, network, server, puppet, database, application ]
config:
  network/access_port: 3000
  network/admin_port: 22
  application/repository_url: git://github.com/opdemand/c2-nodejs-helloworld.git
stack:
  - name: Security
    description: Provides security infrastructure
    components:
      - type: aws-keypair
  - name: Network
    description: Provides network infrastructure
    components:
      - type: aws-sg
  - name: Database
    description: Provides database services
    components:
      - type: aws-instance
        name: PostgreSQL
        config:
          server/hostname: postgres
          server/build_script: build.sh
          server/deploy_script: deploy.db.sh
        output:
          database/host: public_dns_name
    monitor:
      protocol: tcp
      port: 5432
  - name: Application
    description: Provides application services
    components:
      - type: aws-instance
        name: Node.js
        config:
          server/hostname: node
          server/build_script: build.sh
          server/deploy_script: deploy.app.sh
        output:
          network/access_host: public_dns_name
          network/admin_host: public_dns_name
    monitor:
      protocol: tcp
      port: 3000
publish:
  - name: Admin URL
    description: URL used to administer this service
    template: ssh://ubuntu@%(network/admin_host)s
  - name: Database Admin URL
    description: URL used to access this service
    template: ssh://%(database/host)s:%(network/admin_port)s
  - name: Access URL
    description: URL used to access this service
    template: http://%(network/access_host)s:%(network/access_port)s
