# -*- test-case-name: c2server.tests.platform.Apache2DevTest -*-
name: Apache2 Development
path: apache2/dev
include: [ aws, base, network, server ]
config:
  network/access_port: 80
  network/admin_port: 22
stack:
  - name: Security
    description: Provides security infrastructure
    include: [ ] 
    components:
      - type: aws-keypair
        include: [ ] 
  - name: Network
    description: Provides network infrastructure
    include: [ ] 
    components:
      - type: aws-sg
        include: [ network ] 
  - name: Server
    description: Provides generic services
    include: [ ] 
    components:
      - type: aws-instance
        name: Apache2
        include: [ network, server, aws ] 
        config:
          server/hostname: apache2
          server/build_script: build.sh
          server/deploy_script: deploy.sh
        output:
          network/access_host: public_dns_name
          network/admin_host: public_dns_name
    monitor:
      protocol: tcp
      port: 80
publish:
  - name: Admin URL
    description: URL used to administer this service
    template: ssh://ubuntu@%(network/admin_host)s
  - name: Access URL
    description: URL used to access this service
    template: http://%(network/access_host)s
