# -*- test-case-name: c2server.tests.platform.Apache2DevTest -*-
name: Apache2 Development
path: apache2/dev
config: [ aws, base, network, server ]
network:
  admin:
    protocol: ssh
    port: 22
  access:
    protocol: http
    port: 80
stack:
  - name: Security
    description: Provides security infrastructure
    components:
      aws-keypair:
  - name: Network
    description: Provides network infrastructure
    components:
      aws-sg:
  - name: Server
    description: Provides generic services
    components:
      aws-instance:
        name: Apache2
        config:
          server/hostname: apache2
          server/build_script: build.sh
          server/deploy_script: deploy.sh
    monitor:
      protocol: tcp
      port: 80

