# -*- test-case-name: c2server.tests.platform.RailsPostgresql1nodeTest -*-
name: Rails/PostgreSQL 1-node
description: >
             Single node Ruby on Rails environment consisting of a Key Pair,
             Security Group, and an EC2 instance. Installs Rails and a
             PostgreSQL database. Starts multiple Rails servers powered by
             Thin with an Nginx-frontend listening at 80/tcp, all
             powered by a configurable GitHub repositories.
path: rails/postgresql/1node
include: [ aws, base, network, server, puppet, database, application ]
config:
  network/access_port: 80
  network/admin_port: 22
  database/username: rails
  database/password: changeme123.
  database/type: postgresql
  database/port: 5432
  application/repository_url: git://github.com/opdemand/c2-rails-helloworld.git
stack:
  - name: Security
    description: Provides security infrastructure
    include: [ ]
    components:
      - type: aws-keypair
        include: [ ]
  - name: Network
    description: Provides network infrastructure
    include: [ ]
    components:
      - type: aws-sg
        include: [ network ]
  - name: Application
    description: Provides applications services
    include: [ ] 
    components:
      - type: aws-instance
        include: [ network, aws, server, puppet, database, application ] 
        name: Rails
        config:
          server/hostname: rails
          server/build_script: build.sh
          server/deploy_script: deploy.sh
        output:
          network/access_host: public_dns_name
          network/admin_host: public_dns_name
    monitor:
      protocol: tcp
      port: 80
publish:
  - name: Access URL
    description: URL used to access this service
    template: http://%(network/access_host)s
  - name: SSH URL
    description: URL used to administer this server
    template: ssh://ubuntu@%(network/admin_host)s
