# -*- test-case-name: c2server.tests.platform.PyramidDevTest -*-
name: Pyramid Web Development
description: >
             Pyramid python web development environment consisting of a Key
             Pair, Security Group, and an EC2 instance. Installs an Ubuntu
             Oneiric server with Pyramid, powered by a configurable GitHub repository.
path: pyramid/dev
include: [ aws, base, network, server ]
config:
  network/access_port: 22
  network/admin_port: 22
stack:
  - name: Security
    description: Provides security infrastructure
    components:
      - type: aws-keypair
  - name: Network
    description: Provides network infrastructure
    components:
      - type: aws-sg
  - name: Server
    description: Provides generic services
    components:
      - type: aws-instance
        name: Ubuntu
        config:
          server/hostname: ubuntu
          server/build_script: build.sh
          server/deploy_script: deploy.sh
        output:
          network/access_host: public_dns_name
          network/admin_host: public_dns_name
    monitor:
      protocol: tcp
      port: 22
publish:
  - name: Admin URL
    description: URL used to administer this service
    template: ssh://ubuntu@%(network/admin_host)s
  - name: Access URL
    description: URL used to access this service
    template: http://%(network/access_host)s:8080/hello/world