# -*- test-case-name: c2server.tests.platform.NodejsMongodb1nodeTest -*-
name: Node.js/MongoDB 1-node
description: >
             Single server Node.js platform consisting of a Key Pair, Security
             Group and an EC2 instance. Installs a MongoDB server listening at
             27017/tcp and a Node.js server listening at 5000/tcp 
             powered by an open-source GitHub repository.
path: nodejs/mongodb/1node
include: [ aws, base, network, server, puppet, database, application ]
config:
  network/access_port: 5000
  network/admin_port: 22
stack:
  - name: Security
    description: Provides security infrastructure
    include: [ ]
    components:
      - type: aws-keypair
        include: [ ]
  - name: Network
    description: Provides network infrastructure
    include: [ ]
    components:
      - type: aws-sg
        include: [ network ]
  - name: Server
    description: Provides application and database services
    include: [ ]
    components:
      - name: Node.js/MongoDB
        include: [ network, server, puppet, aws, database, application ]
        description: EC2 instance that runs MongoDB service
        type: aws-instance
        config:
          server/hostname: server
          server/build_script: build.sh
          server/deploy_script: deploy.sh
        output:
          network/access_host: public_dns_name
          network/admin_host: public_dns_name
    monitor:
      protocol: tcp
      port: 5000
publish:
  - name: Access URL
    description: Driver URL used to access this service
    template: http://%(network/access_host)s:%(network/access_port)s
