# -*- test-case-name: c2server.tests.platform.UbuntuDevTest -*-
name: Ubuntu Oneiric Development
path: ubuntu/dev
include: [ aws, base, network, server ]
config:
  network/access_port: 22
  network/admin_port: 22
stack:
  - name: Security
    description: Provides security infrastructure
    components:
      - type: aws-keypair
  - name: Network
    description: Provides network infrastructure
    components:
      - type: aws-sg
  - name: Server
    description: Provides generic services
    components:
      - type: aws-instance
        name: Ubuntu
        config:
          server/hostname: ubuntu
          server/build_script: build.sh
          server/deploy_script: deploy.sh
        output:
          network/access_host: public_dns_name
          network/admin_host: public_dns_name
    monitor:
      protocol: tcp
      port: 22
publish:
  - name: Admin URL
    description: URL used to administer this service
    template: ssh://ubuntu@%(network/admin_host)s
