# -*- test-case-name: c2server.tests.platform.UbuntuDevTest -*-
name: Ubuntu Precise Development
description: >
             Ubuntu development environment consisting of a Key Pair, Security
             Group, and an EC2 instance. Installs an Ubuntu Precise server,
             powered by a configurable GitHub repository.
path: ubuntu/dev
include: [ aws, base, network, server ]
config:
  network/access_port: 22
  network/admin_port: 22
stack:
  - name: Security
    description: Provides security infrastructure
    include: [ ]
    components:
      - type: aws-keypair
        include: [ ]
  - name: Network
    description: Provides network infrastructure
    include: [ ] 
    components:
      - type: aws-sg
        include: [ network ] 
  - name: Server
    description: Provides generic services
    include: [ ] 
    components:
      - type: aws-instance
        include: [ aws, network, server ] 
        name: Ubuntu
        config:
          server/hostname: ubuntu
          server/build_script: build.sh
          server/deploy_script: deploy.sh
        output:
          network/access_host: public_dns_name
          network/admin_host: public_dns_name
    monitor:
      protocol: tcp
      port: 22
publish:
  - name: Admin URL
    description: URL used to administer this service
    template: ssh://ubuntu@%(network/admin_host)s
