# default configuration values
config:
  # puppet configuration
  puppet/classes: [ "opdemand::database::mysql" ]
  # database configuration
  database/username: admin
  database/password: changeme123.
  database/port: 3306
  database/type: mysql
  # network configuration
  network/access_cidr: 0.0.0.0/0 # SECURITY: change to allow only trusted source networks
  network/access_port: 3306
# publish to platform consumers
publish:
  - name: Database URL
    description: URL used to access this database
    template: mysql://%(network/access_host)s:%(network/access_port)s
