# -*- test-case-name: c2server.tests.platform.PythonMongodb1x1Test -*-
name: Python/MongoDB 1x1
description: >
             Python application environment consisting of a Key Pair, Security Group, and
             two EC2 instances. Installs the MongoDB document store on one
             instance and a Python web application on the other, listening on 5000/tcp, 
             all powered by a configurable GitHub repository.
path: python/mongodb/1x1
include: [ aws, base, network, server, puppet, application, database ]
config:
  network/access_port: 5000
  network/admin_port: 22
  application/repository_url: git://github.com/opdemand/example-python-flask.git
  database/password: changeme123.
stack:
  - name: Security
    description: Provides security infrastructure
    include: [ ]
    components:
      - type: aws-keypair
        include: [ ]
  - name: Network
    description: Provides network infrastructure
    include: [ ]
    components:
      - type: aws-sg
        include: [ network ]
  - name: Database
    description: Provides database services
    include: [ ]
    components:
      - type: aws-instance
        include: [ network, database, aws, server, puppet  ]
        name: MongoDB
        config:
          server/hostname: mongo
          server/build_script: build.sh
          server/deploy_script: deploy.db.sh
        output:
          database/host: public_dns_name
    monitor:
      protocol: tcp
      port: 27017
  - name: Application
    description: Provides database services
    include: [ ]
    components:
      - type: aws-instance
        include: [ network, application, aws, server, puppet  ]
        name: Python
        config:
          server/hostname: python
          server/build_script: build.sh
          server/deploy_script: deploy.app.sh
        output:
          network/access_host: public_dns_name
          network/admin_host: public_dns_name
    monitor:
      protocol: tcp
      port: 5000
publish:
  - name: Access URL
    description: URL used to access this service
    template: http://%(network/access_host)s:%(network/access_port)s
