# -*- test-case-name: c2server.tests.platform.NodejsRedis1nodeest -*-
name: Node.js/Redis 1-node
description: >
             Single server Node.js environment consisting of a Key Pair, Security Group and
             EC2 instance.  Installs latest compiled node available via Ubuntu PPAs.
             Starts a Redis server and Node.js listening on 3000/tcp, powered by a
             configurable GitHub repository.
path: nodejs/redis/1node
include: [ aws, base, network, server, puppet, application, cache ]
config:
  network/access_port: 3000
  network/admin_port: 22
  application/repository_url: git://github.com/opdemand/c2-nodejs-helloworld.git
  cache/password: changeme123.
stack:
  - name: Security
    description: Provides security infrastructure
    include: [ ]
    components:
      - type: aws-keypair
        include: [ ]
  - name: Network
    description: Provides network infrastructure
    include: [ ]
    components:
      - type: aws-sg
        include: [ network ]
  - name: Server
    description: Provides generic services
    include: [ ] 
    components:
      - type: aws-instance
        include: [ network, aws, server, puppet, application, cache ] 
        name: Node.js
        config:
          server/hostname: node
          server/build_script: build.sh
          server/deploy_script: deploy.sh
        output:
          network/access_host: public_dns_name
          network/admin_host: public_dns_name
    monitor:
      protocol: tcp
      port: 3000
publish:
  - name: Admin URL
    description: URL used to administer this service
    template: ssh://ubuntu@%(network/admin_host)s
  - name: Access URL
    description: URL used to access this service
    template: http://%(network/access_host)s:%(network/access_port)s
