name: Node.js (2-node)
path: nodejs/2node
config: [ aws, base, network, server, application ]
network:
  admin:
    protocol: ssh
    port: 22
  access:
    protocol: http
    port: 3000
stack:
  - name: Security
    description: Provides security infrastructure
    components:
      aws-keypair:
  - name: Network
    description: Provides network infrastructure
    components:
      aws-sg:
  - name: Server
    description: Provides generic services
    components:
      aws-instance-1:
        name: "Node.js 1"
        config:
          server/hostname: node2
          server/build_script: build.sh
          server/deploy_script: deploy.sh
          application/repository_url: git://github.com/opdemand/c2-nodejs-helloworld.git
        output:
          lb/instances: [ instance_id ]
      aws-instance-2:
        name: "Node.js 2"
        config:
          server/hostname: node2
          server/build_script: build.sh
          server/deploy_script: deploy.sh
          application/repository_url: git://github.com/opdemand/c2-nodejs-helloworld.git
        output:
          lb/instances: [ instance_id ]
    monitor:
      protocol: tcp
      port: 3000
  - name: Load Balancing
    description: Provides load balancing services
    components:
      aws-elb:
        name: "ELB"
        config:
          lb/listeners: [ "(80, 3000, TCP)" ]
          lb/target: HTTP:3000/
    monitor:
      protocol: tcp
      port: 80
      target: dns_name
