# -*- test-case-name: c2server.tests.platform.PostgresqlDevTest -*-
name: PostgreSQL Development
path: postgresql/dev
include: [ aws, base, network, server, puppet, database ]
config:
  network/access_port: 5432
  network/admin_port: 22
stack:
  - name: Security
    description: Provides security infrastructure
    include: [ ]
    components:
      - type: aws-keypair
        include: [ ]
  - name: Network
    description: Provides network infrastructure
    include: [ ] 
    components:
      - type: aws-sg
        include: [ network ] 
  - name: Database
    description: Provides database services
    include: [ ] 
    components:
      - type: aws-instance
        include: [ aws, network, server, puppet, database ] 
        name: PostgreSQL
        config:
          server/hostname: postgres
          server/build_script: build.sh
          server/deploy_script: deploy.sh
        output:
          network/access_host: public_dns_name
          network/admin_host: public_dns_name
    monitor:
      protocol: tcp
      port: 5432
publish:
  - name: Admin URL
    description: URL used to administer this service
    template: ssh://ubuntu@%(network/admin_host)s
  - name: Access URL
    description: URL used to access this service
    template: http://%(network/access_host)s:%(network/access_port)s
