# -*- test-case-name: c2server.tests.platform.MysqlRdsTest -*-
name: MySQL RDS 1-node
description: >
             Managed MySQL environment consisting of a Key Pair, Security
             Group, and an RDS instance. Creates an RDS MySQL server listening
             at 3306/tcp.
path: mysql/rds
include: [ aws, base, network, relationaldb ]
config:
  network/access_port: 3306
  network/admin_port: 3306
stack:
  - name: Security
    description: Provides security infrastructure
    include: [ ] 
    components:
      - type: aws-keypair
        include: [ ] 
  - name: Network
    description: Provides network infrastructure
    include: [ ] 
    components:
      - type: aws-sg
        include: [ aws, network ] 
      - type: aws-rdssg
        include: [ ]
  - name: Database
    description: Provides database services
    include: [ ] 
    components:
      - type: aws-rdsinstance
        include: [ aws, relationaldb ] 
        name: RDS MySQL
        output:
          network/access_host: public_dns_name
          network/admin_host: public_dns_name
    monitor:
      protocol: tcp
      port: 3306
publish:
  - name: Access URL
    description: URL used to access this service
    template: mysql://%(network/access_host)s:3306
