# default configuration values
config:
  # puppet configuration
  puppet/classes: [ "opdemand::database::mongodb" ]
  # database configuration
  database/username: admin
  database/password: changeme123.
  database/port: 27017
  database/type: mongodb
  # network configuration
  network/access_cidr: 0.0.0.0/0 # SECURITY: change to allow only trusted source networks
  network/access_port: 27017
# publish to platform consumers
publish_include: [ mongodb ]
export_include: [ db ]
