# -*- test-case-name: c2server.tests.platform.RailsPostgresqlElb2x1Test -*-
name: Rails/PostgreSQL 2x1 with ELB
description: >
             Ruby on Rails environment consisting of a Key Pair, Security Group, three
             EC2 instances, and a load balancer all powered by configurable GitHub repositories.
             Installs the PostgreSQL database on one instance and the Ruby on Rails 
             web framework on the other two. Sets up the load balancer to 
             listen on 80/tcp and distribute traffic across the two Rails servers running Thin/Nginx.
path: rails/postgresql/elb2x1
include: [ aws, base, network, server, puppet, database, application ]
config:
  network/access_port: 80
  network/admin_port: 22
  database/username: rails
  database/password: changeme123.
  database/type: postgresql
  database/port: 5432
  application/repository_url: git://github.com/opdemand/c2-rails-helloworld.git
stack:
  - name: Security
    description: Provides security infrastructure
    include: [ ]
    components:
      - type: aws-keypair
        include: [ ]
  - name: Network
    description: Provides network infrastructure
    include: [ ]
    components:
      - type: aws-sg
        include: [ network ]
  - name: Database
    description: Provides database services
    include: [ ]
    components:
      - type: aws-instance
        include: [ aws, network, server, puppet, database ]
        name: PostgreSQL
        config:
          server/hostname: postgres
          server/build_script: build.sh
          server/deploy_script: deploy.db.sh
        output:
          database/host: public_dns_name
    monitor:
      protocol: tcp
      port: 5432
  - name: Application
    description: Provides database services
    include: [ ]
    components:
      - type: aws-instance
        include: [ aws, network, server, puppet, application ]
        name: Rails 1
        config:
          server/hostname: rails1
          server/build_script: build.sh
          server/deploy_script: deploy.app.sh
        output:
          lb/instances: [ instance_id ]
      - type: aws-instance
        include: [ aws, network, server, puppet, application ]
        name: Rails 2
        config:
          server/hostname: rails2
          server/build_script: build.sh
          server/deploy_script: deploy.app.sh
        output:
          lb/instances: [ instance_id ]
    monitor:
      protocol: tcp
      port: 80
  - name: Load Balancing
    description: Provides load balancing services
    include: [ ] 
    components:
      - type: aws-elb
        include: [ ] 
        name: ELB
        config:
          lb/listeners: [ "(80, 80, TCP)" ]
          lb/target: HTTP:80/
        output:
          network/access_host: dns_name
          network/admin_host: dns_name
    monitor:
      protocol: tcp
      port: 80
      target: dns_name
publish:
  - name: Access URL
    description: URL used to access this service
    template: http://%(network/access_host)s
