# -*- test-case-name: c2server.tests.platform.DjangoPostgresqlDevTest -*-
name: Django/PostgreSQL Dual Node
path: django/postgresql/dual
include: [ aws, base, network, server, database, application ]
config:
  network/access_port: 8080
  network/admin_port: 22
  database/username: django
  database/password: changeme123.
  application/repository_url: git://github.com/gabrtv/c2-django-helloworld.git
stack:
  - name: Security
    description: Provides security infrastructure
    components:
      - type: aws-keypair
  - name: Network
    description: Provides network infrastructure
    components:
      - type: aws-sg
  - name: Database
    description: Provides database services
    components:
      - type: aws-instance
        name: PostgreSQL
        config:
          server/hostname: postgres
          server/build_script: build.db.sh
          server/deploy_script: deploy.db.sh
        output:
          database/host: public_dns_name
  - name: Application
    description: Provides database services
    components:
      - type: aws-instance
        name: Django
        config:
          server/hostname: django
          server/build_script: build.app.sh
          server/deploy_script: deploy.app.sh
        output:
          network/access_host: public_dns_name
          network/admin_host: public_dns_name
    monitor:
      protocol: tcp
      port: 8080
publish:
  - name: Admin URL
    description: URL used to administer this service
    template: http://%(network/admin_host)s/admin/
  - name: Access URL
    description: URL used to access this service
    template: http://%(network/access_host)s:%(network/access_port)d
